/*
 * Projeto Muse.
 * Gerenciamento Hoteleiro
 *  I.T WORKS.
 */
package br.com.muse.gui;

import br.com.muse.beans.ApartamentoBean;
import br.com.muse.controller.ApartamentosControle;
import br.com.muse.util.Mensagem;
import br.com.muse.util.Propriedade;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.beans.PropertyVetoException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kennedy
 */
public class ApartamentosGUI extends javax.swing.JInternalFrame implements IPosicaoGUI{

    private String modo;
    public DefaultTableModel modelo;
    private ApartamentosControle apartamentosC = new ApartamentosControle();
    private ApartamentoBean apartamentoAtual =  new ApartamentoBean();
    private int apartamentoSelecionado = 0;
    
    /**
     * Creates new form ApartamentosGUI
     */
    public ApartamentosGUI() {
        
        
        initComponents();
        this.bt_deletar.setEnabled(false);
        modelo = (DefaultTableModel) tabela.getModel();
        popularNumeros();
        listarApartamentos();
                
    }
    
    @Override
    public void ajustar(Dimension d) {
        
        this.setLocation((d.width - this.getSize().width) / 2, 10);
        
        try {
            this.setSelected(true);
            
        } catch (PropertyVetoException ex) {
        
            
        }
        
    }
    
    private void popularNumeros() {
        
        for(int x=1;x<=250;x++) if(Propriedade.getProp("apartamentos.properties", "apt"+x).equals("AVULSO")) this.cb_numero.addItem(x);
    }
    

    private boolean confirmarSenha() {
        
        ApartamentosControle ApConfig = new ApartamentosControle();
        JPanel panel = new JPanel(new GridLayout(3,1));

        JLabel label1 = new JLabel("Para confirmar as alterações");
        JLabel label2 = new JLabel("Digite sua senha atual:");
        JPasswordField pass = new JPasswordField(22);

        panel.add(label1);
        panel.add(label2);
        panel.add(pass);
        
        String[] options = new String[]{"Confirmar", "Cancelar"};
        
        int option = JOptionPane.showOptionDialog(null, panel, "Manutenção",JOptionPane.NO_OPTION, 2,null, options, pass);

        if (option == 0) if(ApConfig.autenticar(new String(pass.getPassword()))) return true; else Mensagem.erroMsg("Falha na autenticação!\nDigite a senha atual do administrador do sistema!", "Manutenção");
        
        return false;        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        bt_cancelar = new javax.swing.JButton();
        bt_cadastrar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        bt_deletar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cb_numero = new javax.swing.JComboBox();

        setClosable(true);
        setResizable(true);
        setTitle("Gerenciar apartamentos");
        setVisible(true);

        jLabel4.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        jLabel4.setText("Listar");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº", "Alugado", "Reservado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabelaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(0).setMinWidth(50);
            tabela.getColumnModel().getColumn(0).setPreferredWidth(50);
            tabela.getColumnModel().getColumn(0).setMaxWidth(60);
            tabela.getColumnModel().getColumn(1).setMinWidth(70);
            tabela.getColumnModel().getColumn(1).setPreferredWidth(70);
            tabela.getColumnModel().getColumn(1).setMaxWidth(86);
            tabela.getColumnModel().getColumn(2).setMinWidth(80);
            tabela.getColumnModel().getColumn(2).setPreferredWidth(80);
            tabela.getColumnModel().getColumn(2).setMaxWidth(90);
        }

        bt_cancelar.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        bt_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cancel_icon.png"))); // NOI18N
        bt_cancelar.setText("Cancelar");
        bt_cancelar.setPreferredSize(new java.awt.Dimension(60, 27));
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        bt_cadastrar.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        bt_cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/user_add_icon.png"))); // NOI18N
        bt_cadastrar.setText("Cadastrar");
        bt_cadastrar.setPreferredSize(new java.awt.Dimension(60, 27));
        bt_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastrarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        jLabel8.setText("Cadastrar");

        bt_deletar.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        bt_deletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/remover_icon.png"))); // NOI18N
        bt_deletar.setText("Excluir");
        bt_deletar.setPreferredSize(new java.awt.Dimension(60, 27));
        bt_deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deletarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel9.setText("Numero:");

        cb_numero.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bt_deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bt_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bt_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(bt_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(bt_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed

        this.dispose();
    }//GEN-LAST:event_bt_cancelarActionPerformed

    private void bt_deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deletarActionPerformed

        if(confirmarSenha()) {
        
        int id = apartamentosC.buscarPorId(apartamentoSelecionado).getNum_quarto();
        
        if(apartamentosC.removerApartamento(apartamentoSelecionado)) {
            
            Propriedade.setProp("apartamentos.properties", "apt"+id, "AVULSO");
            this.cb_numero.removeAllItems();
            popularNumeros();
            listarApartamentos();
            this.bt_deletar.setEnabled(false);
        }
        
       }
        
    }//GEN-LAST:event_bt_deletarActionPerformed

    private void bt_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadastrarActionPerformed
        
        if(confirmarSenha()) {
            
            apartamentoAtual = new ApartamentoBean();
            
            //Dados do quarto
            String num = String.valueOf(cb_numero.getSelectedItem());     
            
            apartamentoAtual.setNum_quarto(Integer.parseInt(num));
     
            System.out.println("apt"+num);
            if(apartamentosC.cadastrar(apartamentoAtual)) {
                
                Propriedade.setProp("apartamentos.properties", "apt"+num, "CADASTRADO");
                
                this.cb_numero.removeAllItems();
                popularNumeros();
                listarApartamentos();
            }
            else Mensagem.erroMsg("Falha ao cadastrar o apartamento", "Houve uma erro");
        }
    }//GEN-LAST:event_bt_cadastrarActionPerformed

    private void tabelaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMousePressed
        
        apartamentoAtual = new ApartamentoBean();

        String num_quarto = String.valueOf(tabela.getValueAt(tabela.getSelectedRow(), 0));
        
        apartamentoAtual = apartamentosC.buscarApartamento(num_quarto);
        
        apartamentoSelecionado = apartamentoAtual.getId_quarto();
        
        if(!apartamentoAtual.isAlugado() && !apartamentoAtual.isReservado()) this.bt_deletar.setEnabled(true);
        
        else this.bt_deletar.setEnabled(false);                
    }//GEN-LAST:event_tabelaMousePressed

    private void listarApartamentos() {
        
        this.modelo.setNumRows(0);
        
        apartamentosC.mostrarApartamentos(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cadastrar;
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_deletar;
    private javax.swing.JComboBox cb_numero;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables

    
}
