/*
 * Projeto Muse.
 * Gerenciamento Hoteleiro
 *  I.T WORKS.
 */
package br.com.muse.gui;

import br.com.muse.beans.CheckInBean;
import br.com.muse.beans.CheckOutBean;
import br.com.muse.beans.ReservaBean;
import br.com.muse.controller.CheckInControle;
import br.com.muse.controller.CheckOutControle;
import br.com.muse.controller.ReservaControle;
import br.com.muse.util.Mensagem;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.beans.PropertyVetoException;
import java.text.NumberFormat;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kennedy
 */
public class CheckOutGUI extends javax.swing.JInternalFrame implements IPosicaoGUI{
    
    NumberFormat doubleformat = NumberFormat.getInstance();
    public DefaultTableModel modelo;

    /**
     * Creates new form CheckOutGUI
     */
    public CheckOutGUI() {
        initComponents();
        modelo = (DefaultTableModel) tabela.getModel();
        listarCheckOuts();
    }
    
    @Override
    public void ajustar(Dimension d) {
        
        this.setLocation((d.width - this.getSize().width) / 2, 10);
        
        try {
            this.setSelected(true);
            
        } catch (PropertyVetoException ex) {
        
            
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tf_pesquisar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        bt_cancelar = new javax.swing.JButton();
        bt_cjeck_out = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Gerenciar check out");
        setVisible(true);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Check Out", "Hospede", "Quarto", "Fatura"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(0).setMinWidth(110);
            tabela.getColumnModel().getColumn(0).setPreferredWidth(110);
            tabela.getColumnModel().getColumn(0).setMaxWidth(110);
            tabela.getColumnModel().getColumn(1).setMinWidth(450);
            tabela.getColumnModel().getColumn(1).setPreferredWidth(450);
            tabela.getColumnModel().getColumn(1).setMaxWidth(450);
            tabela.getColumnModel().getColumn(2).setMinWidth(110);
            tabela.getColumnModel().getColumn(2).setPreferredWidth(110);
            tabela.getColumnModel().getColumn(2).setMaxWidth(110);
            tabela.getColumnModel().getColumn(3).setMinWidth(110);
            tabela.getColumnModel().getColumn(3).setPreferredWidth(110);
            tabela.getColumnModel().getColumn(3).setMaxWidth(110);
        }

        jLabel1.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel1.setText("Check Out:");

        tf_pesquisar.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        tf_pesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_pesquisarKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        jLabel6.setText("Pesquisar:");

        bt_cancelar.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        bt_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cancel_icon.png"))); // NOI18N
        bt_cancelar.setText("Cancelar");
        bt_cancelar.setPreferredSize(new java.awt.Dimension(60, 27));
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        bt_cjeck_out.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        bt_cjeck_out.setText("Check Out");
        bt_cjeck_out.setPreferredSize(new java.awt.Dimension(60, 27));
        bt_cjeck_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cjeck_outActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bt_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt_cjeck_out, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(17, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_cjeck_out, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                        .addComponent(bt_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_pesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_pesquisarKeyReleased

        CheckOutControle checkOutC = new CheckOutControle();

        checkOutC.pesquisarCheckOut(modelo, tf_pesquisar.getText());
    }//GEN-LAST:event_tf_pesquisarKeyReleased

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed

        this.dispose();
    }//GEN-LAST:event_bt_cancelarActionPerformed

    
    
    
    private void bt_cjeck_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cjeck_outActionPerformed

        this.bt_cjeck_out.setEnabled(false);

        JPanel panel = new JPanel(new GridLayout(3,1));
        JLabel label1 = new JLabel("Informe o numero do Check In:");
        JComboBox checkins = new JComboBox();
        panel.add(label1);
        panel.add(checkins);

        String[] options = new String[]{"Confirmar", "Cancelar"};

        CheckInControle checkInC = new CheckInControle();

        ArrayList<CheckInBean> todos = checkInC.mostrarTodos();

        if(todos.size() > 0) {

            for(CheckInBean t : todos) {

                checkins.addItem(t);
            }

            int option = JOptionPane.showOptionDialog(null, panel, "Check Out",JOptionPane.NO_OPTION, 2,null, options, checkins);

            if (option == 0) {

                if(checkOut(Integer.parseInt(String.valueOf(checkins.getSelectedItem())))) {

                    listarCheckOuts();
                    Mensagem.okMsg("Check Out efetuado com sucesso!", "Sucesso");                    
                    this.tf_pesquisar.requestFocus();
                }
            }

        }
        else {

            Mensagem.erroMsg("Não há check ins efetuados!", "Houve um erro");

        }

    }//GEN-LAST:event_bt_cjeck_outActionPerformed

    private void listarCheckOuts() {
        
        CheckOutControle checkOutC = new CheckOutControle();
        
        this.modelo.setNumRows(0);
        
        checkOutC.mostrarCheckOuts(modelo);        
    }
    
    private boolean checkOut(int id) {
        
        CheckOutControle checkOutC = new CheckOutControle();
        CheckInControle checkInC = new CheckInControle();
        CheckOutBean checkOutB = new CheckOutBean();
        CheckInBean checkInB = new CheckInBean();
        
        //Recupera o Check In
        checkInB = checkInC.buscarPorId(id);
        
        checkOutB.setId_hospede(checkInB.getId_hospede());
        checkOutB.setId_quarto(checkInB.getId_quarto());
        checkOutB.setValorFatura(0);
        
        checkInC.remover(id);
                        
        return checkOutC.efetuarCheckOut(checkOutB);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_cjeck_out;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField tf_pesquisar;
    // End of variables declaration//GEN-END:variables

    
}
