/*
 * Projeto Muse.
 * Gerenciamento Hoteleiro
 *  I.T WORKS.
 */
package br.com.muse.gui;

import br.com.muse.controller.ConfigurarBDControle;
import br.com.muse.util.Mensagem;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;

/**
 *
 * @author kennedy
 */
public class ConfigurarBDGUI extends javax.swing.JInternalFrame implements IPosicaoGUI{

    /**
     * Creates new form ConfigurarBDGUI
     */
    public ConfigurarBDGUI() {
        
                       
        initComponents();    
        mostrarConfigs();
    }
    
    @Override
    public void ajustar(Dimension d) {
        
        this.setLocation((d.width - this.getSize().width) / 2, 10);
        
        try {
            this.setSelected(true);
            
        } catch (PropertyVetoException ex) {
        
            
        }
        
    }
    
    private void mostrarConfigs() {
        
        ConfigurarBDControle configs = new ConfigurarBDControle();
        ArrayList<String> c = new ArrayList<>();        
        c = configs.carregar();
        
        tf_host.setText(c.get(0));
        tf_porta.setText(c.get(1));
        tf_base.setText(c.get(2));
        tf_usuario.setText(c.get(3));
        pf_senha.setText(c.get(4));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_host = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_porta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_base = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_usuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bt_salvar = new javax.swing.JButton();
        bt_cancelar = new javax.swing.JButton();
        bt_reset = new javax.swing.JButton();
        pf_senha = new javax.swing.JPasswordField();
        bt_testar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Configurar banco de dados");
        setVisible(true);

        jLabel1.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nos campos abaixo, defina as configurações do banco de dados:");

        jLabel2.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel2.setText("Servidor:");

        tf_host.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel3.setText("Porta:");

        tf_porta.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel4.setText("Schema:");

        tf_base.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel5.setText("Usuario:");

        tf_usuario.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel6.setText("Senha:");

        jLabel7.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel7.setText("(Padrão: 3306)");

        bt_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/apply_icon.png"))); // NOI18N
        bt_salvar.setText("Salvar");
        bt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salvarActionPerformed(evt);
            }
        });

        bt_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cancel_icon.png"))); // NOI18N
        bt_cancelar.setText("Cancelar");
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        bt_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/reset_icon.png"))); // NOI18N
        bt_reset.setText("Redefinir");
        bt_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_resetActionPerformed(evt);
            }
        });

        bt_testar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/pass_icon.png"))); // NOI18N
        bt_testar.setText("Testar Configuração");
        bt_testar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_testarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_host, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(pf_senha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                .addComponent(tf_usuario, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_base, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_porta, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addComponent(bt_testar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_host, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tf_porta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pf_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_testar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salvarActionPerformed
        
        if(confirmarSenha()) {
            
            ArrayList<String> s = new ArrayList<>();
            ConfigurarBDControle configurar = new ConfigurarBDControle();        
            s.add(tf_host.getText());
            s.add(tf_porta.getText());
            s.add(tf_base.getText());
            s.add(tf_usuario.getText());
            s.add(new String(pf_senha.getPassword()));
            configurar.alterar(s);
            
            this.dispose();
            Mensagem.okMsg("As configurações foram salvas!", "Manutenção");            
        }        
    }//GEN-LAST:event_bt_salvarActionPerformed

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed

        
        this.dispose();
    }//GEN-LAST:event_bt_cancelarActionPerformed

    private void bt_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_resetActionPerformed

        if(confirmarSenha()) {
            
            ConfigurarBDControle configurar = new ConfigurarBDControle();            
            configurar.redefinir();
            mostrarConfigs();
            Mensagem.okMsg("As configurações foram restauradas com sucesso!", "Manutenção");            
        }
        
    }//GEN-LAST:event_bt_resetActionPerformed

    private void bt_testarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_testarActionPerformed
        
        ConfigurarBDControle configurar = new ConfigurarBDControle();
        
        if(configurar.testarConexao(tf_host.getText(), tf_porta.getText(), tf_base.getText(), tf_usuario.getText(), new String(pf_senha.getPassword()))) Mensagem.okMsg("Conexao bem sucedida!", "Manutenção");
        
        else Mensagem.erroMsg("Não foi possível conectar\nVerifique as configurações!", "Manutenção");
        
    }//GEN-LAST:event_bt_testarActionPerformed

    private boolean confirmarSenha() {
        
        ConfigurarBDControle configurar = new ConfigurarBDControle();
        JPanel panel = new JPanel(new GridLayout(3,1));
        JLabel label1 = new JLabel("Para confirmar as alterações");
        JLabel label2 = new JLabel("Digite sua senha atual:");
        JPasswordField pass = new JPasswordField(22);
        panel.add(label1);
        panel.add(label2);
        panel.add(pass);
        
        String[] options = new String[]{"Confirmar", "Cancelar"};
        
        int option = JOptionPane.showOptionDialog(null, panel, "Manutenção",JOptionPane.NO_OPTION, 2,null, options, pass);

        if (option == 0) if(configurar.autenticar(new String(pass.getPassword()))) return true; else Mensagem.erroMsg("Falha na autenticação!\nDigite a senha atual do administrador do sistema!", "Manutenção");
        
        return false;        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_reset;
    private javax.swing.JButton bt_salvar;
    private javax.swing.JButton bt_testar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField pf_senha;
    private javax.swing.JTextField tf_base;
    private javax.swing.JTextField tf_host;
    private javax.swing.JTextField tf_porta;
    private javax.swing.JTextField tf_usuario;
    // End of variables declaration//GEN-END:variables
}
