/*
 * Projeto Muse.
 * Gerenciamento Hoteleiro
 *  I.T WORKS.
 */
package br.com.muse.gui;


import br.com.muse.beans.FuncionarioBean;
import br.com.muse.gui.lookandfeel.MuseMenuBar;
import br.com.muse.util.Cerbero;
import br.com.muse.util.Mensagem;
import br.com.muse.util.Propriedade;
import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;

/**
 *
 * @author kennedy
 */
public class Muse extends javax.swing.JFrame {
    
    public static int session_time = Integer.parseInt(Propriedade.getProp("museconfig.properties", "muse.tempo"));
    private FuncionarioBean funcionarioAtivo = new FuncionarioBean();
    private boolean adminAut;
    private boolean funcAut;
    private static JDesktopPane desktopS;
    public static double valorDiaria = Double.parseDouble(Propriedade.getProp("museconfig.properties", "muse.diaria"));
    
    /**
     * Creates new form Muse
     */
    public Muse() { 
          
        initComponents();                
        this.adminAut = true;
        this.funcAut = false;
        desktopS = desktop;
        
        setLocationRelativeTo(null);
            
        if(Cerbero.decrypt64(Propriedade.getProp("museconfig.properties", "muse.video")).equalsIgnoreCase("true")) {
            
            desktop.putClientProperty("JDesktopPane.dragMode", "outline");
        }        
    }
    
    public void resetDesktop() {
        
        this.desktop.removeAll();
        this.desktop.repaint();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        topo = new javax.swing.JPanel();
        lb_checkout = new javax.swing.JLabel();
        bt_checkout = new javax.swing.JButton();
        lb_checkin = new javax.swing.JLabel();
        bt_checkin = new javax.swing.JButton();
        lb_reservas = new javax.swing.JLabel();
        bt_reservas = new javax.swing.JButton();
        lb_hospedes = new javax.swing.JLabel();
        bt_hospedes = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        lateral_direita = new javax.swing.JPanel();
        lateral_esquerda = new javax.swing.JPanel();
        rodape = new javax.swing.JPanel();
        barraMenu = new MuseMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Muse v0.4 Beta");
        setBackground(java.awt.Color.gray);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setPreferredSize(new java.awt.Dimension(1024, 768));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        desktop.setBackground(new java.awt.Color(240, 240, 240));
        desktop.setBorder(null);
        desktop.setDoubleBuffered(true);
        getContentPane().add(desktop, java.awt.BorderLayout.CENTER);

        topo.setBackground(new java.awt.Color(190, 197, 200));
        topo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 2, 4, java.awt.Color.GRAY));
        topo.setPreferredSize(new java.awt.Dimension(900, 85));

        lb_checkout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_checkout.setText("Check Out");

        bt_checkout.setBackground(new java.awt.Color(240, 240, 240));
        bt_checkout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/suitcase_icon.png"))); // NOI18N
        bt_checkout.setBorder(null);
        bt_checkout.setBorderPainted(false);
        bt_checkout.setContentAreaFilled(false);
        bt_checkout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_checkoutActionPerformed(evt);
            }
        });

        lb_checkin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_checkin.setText("Check In");

        bt_checkin.setBackground(new java.awt.Color(240, 240, 240));
        bt_checkin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/check_in_icon.png"))); // NOI18N
        bt_checkin.setBorder(null);
        bt_checkin.setBorderPainted(false);
        bt_checkin.setContentAreaFilled(false);
        bt_checkin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_checkin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_checkinActionPerformed(evt);
            }
        });

        lb_reservas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_reservas.setText("Reservas");

        bt_reservas.setBackground(new java.awt.Color(240, 240, 240));
        bt_reservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/calendar_2_icon.png"))); // NOI18N
        bt_reservas.setBorder(null);
        bt_reservas.setBorderPainted(false);
        bt_reservas.setContentAreaFilled(false);
        bt_reservas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_reservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_reservasActionPerformed(evt);
            }
        });

        lb_hospedes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_hospedes.setText("Hospedes");

        bt_hospedes.setBackground(new java.awt.Color(240, 240, 240));
        bt_hospedes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/hospede_icon.png"))); // NOI18N
        bt_hospedes.setContentAreaFilled(false);
        bt_hospedes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_hospedes.setPreferredSize(new java.awt.Dimension(48, 48));
        bt_hospedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hospedesActionPerformed(evt);
            }
        });

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout topoLayout = new javax.swing.GroupLayout(topo);
        topo.setLayout(topoLayout);
        topoLayout.setHorizontalGroup(
            topoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topoLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(bt_hospedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lb_hospedes, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(topoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topoLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(bt_reservas))
                    .addComponent(lb_reservas, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(topoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topoLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(bt_checkin))
                    .addComponent(lb_checkin, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(topoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topoLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(bt_checkout))
                    .addComponent(lb_checkout, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(620, Short.MAX_VALUE))
        );
        topoLayout.setVerticalGroup(
            topoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(topoLayout.createSequentialGroup()
                        .addGroup(topoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_checkout)
                            .addComponent(bt_checkin)
                            .addComponent(bt_reservas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(topoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_checkout)
                            .addComponent(lb_checkin)
                            .addComponent(lb_reservas)))
                    .addGroup(topoLayout.createSequentialGroup()
                        .addComponent(bt_hospedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_hospedes)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(topo, java.awt.BorderLayout.NORTH);

        lateral_direita.setBackground(java.awt.Color.gray);
        lateral_direita.setPreferredSize(new java.awt.Dimension(4, 10));
        getContentPane().add(lateral_direita, java.awt.BorderLayout.LINE_END);

        lateral_esquerda.setBackground(java.awt.Color.gray);
        lateral_esquerda.setPreferredSize(new java.awt.Dimension(4, 10));
        getContentPane().add(lateral_esquerda, java.awt.BorderLayout.LINE_START);

        rodape.setBackground(java.awt.Color.gray);
        rodape.setPreferredSize(new java.awt.Dimension(10, 4));
        getContentPane().add(rodape, java.awt.BorderLayout.PAGE_END);

        barraMenu.setBackground(java.awt.Color.gray);
        barraMenu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 0, 4, java.awt.Color.GRAY));

        jMenu1.setForeground(java.awt.Color.white);
        jMenu1.setText("Manutenção");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Configuração do Muse");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.setMnemonic(KeyEvent.VK_M);
        jMenu1.setDisplayedMnemonicIndex(0);
        jMenu1.add(jSeparator1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Configurar banco de dados");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Alterar Permissões");
        jMenuItem3.setActionCommand("");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator9);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText("Gerenciar funcionários");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);
        jMenu1.add(jSeparator10);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setText("Gerenciar apartamentos");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        barraMenu.add(jMenu1);

        jMenu2.setForeground(java.awt.Color.white);
        jMenu2.setText("Sobre o Muse");

        jMenuItem4.setText("Sobre o Muse");
        jMenu2.add(jMenuItem4);
        jMenu2.add(jSeparator3);

        jMenuItem5.setText("Manual");
        jMenu2.add(jMenuItem5);
        jMenu2.add(jSeparator4);

        jMenuItem6.setText("Sair");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        barraMenu.add(jMenu2);

        setJMenuBar(barraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        
        setExtendedState(JFrame.NORMAL);
        GUIFX g = new GUIFX();
        g.start();
        g.animar(this.getRootPane(), GUIFX.EFEITO_DESAPARECER_E_FECHAR, 1000);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void bt_checkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_checkoutActionPerformed

        int nivel = Integer.parseInt(Propriedade.getProp("permissoes.properties", "checkout.visualizar"));
        
        if(adminAut || funcionarioAtivo.getNivel_acesso() >= nivel) {
            
            CheckOutGUI checkoutGUI = new CheckOutGUI();
            resetDesktop();
            desktop.add(checkoutGUI);
            checkoutGUI.ajustar(desktop.getSize());
        }
        else notificacaoPush("Você não possui a permissão necessária!");
    }//GEN-LAST:event_bt_checkoutActionPerformed

    private void bt_checkinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_checkinActionPerformed

        int nivel = Integer.parseInt(Propriedade.getProp("permissoes.properties", "checkin.visualizar"));
        
        if(adminAut || funcionarioAtivo.getNivel_acesso() >= nivel) {
            
            CheckInGUI checkinGUI = new CheckInGUI();
            resetDesktop();
            desktop.add(checkinGUI);
            checkinGUI.ajustar(desktop.getSize());   
        }
        else notificacaoPush("Você não possui a permissão necessária!");
    }//GEN-LAST:event_bt_checkinActionPerformed

    private void bt_reservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_reservasActionPerformed

        int nivel = Integer.parseInt(Propriedade.getProp("permissoes.properties", "reserva.visualizar"));
        
        if(adminAut || funcionarioAtivo.getNivel_acesso() >= nivel) {

            ReservaGUI reservaGUI = new ReservaGUI();
            resetDesktop();
            desktop.add(reservaGUI);
            reservaGUI.ajustar(desktop.getSize());   
        }
        else notificacaoPush("Você não possui a permissão necessária!");        
        
    }//GEN-LAST:event_bt_reservasActionPerformed

    private void bt_hospedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hospedesActionPerformed

        int nivel = Integer.parseInt(Propriedade.getProp("permissoes.properties", "hospede.visualizar"));
        
        if(adminAut || funcionarioAtivo.getNivel_acesso() >= nivel) {
            
            HospedeGUI hospedeGUI = new HospedeGUI();
            resetDesktop();
            desktop.add(hospedeGUI);
            hospedeGUI.ajustar(desktop.getSize());
        }
        else notificacaoPush("Você não possui a permissão necessária!");
        
    }//GEN-LAST:event_bt_hospedesActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        resetDesktop();
        
        if(adminAut) {
            
            PermissoesGUI permissaoGUI = new PermissoesGUI();
            desktop.add(permissaoGUI);
            permissaoGUI.ajustar(desktop.getSize()); 
        }
        else notificacaoPush("Acesso restrito ao administrador!");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        resetDesktop();

        if(adminAut) {
            
            ConfigurarBDGUI configBDGUI = new ConfigurarBDGUI();
            desktop.add(configBDGUI);
            configBDGUI.ajustar(desktop.getSize());
        }
        else notificacaoPush("Acesso restrito ao administrador!");
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        
        resetDesktop();
        
        if(adminAut) {
            
            ConfigurarMuseGUI configMuseBDGUI = new ConfigurarMuseGUI();
            desktop.add(configMuseBDGUI);
            configMuseBDGUI.ajustar(desktop.getSize());
        }
        else notificacaoPush("Acesso restrito ao administrador!");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
        
        setExtendedState(JFrame.NORMAL);
        
        GUIFX g = new GUIFX();
        g.start();
        g.animar(this.getRootPane(), GUIFX.EFEITO_DESAPARECER_E_FECHAR, 200);
        
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        
        int nivel = Integer.parseInt(Propriedade.getProp("permissoes.properties", "funcionario.visualizar"));
        
        if(adminAut || funcionarioAtivo.getNivel_acesso() >= nivel) {
            
            FuncionarioGUI cad_func = new FuncionarioGUI();
            resetDesktop();
            desktop.add(cad_func);
            cad_func.ajustar(desktop.getSize());
        }
        else notificacaoPush("Você não possui a permissão necessária!");
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed

        int nivel = Integer.parseInt(Propriedade.getProp("permissoes.properties", "apartamento.visualizar"));
        
        if(adminAut || funcionarioAtivo.getNivel_acesso() >= nivel) {

            ApartamentosGUI apGUI = new ApartamentosGUI();
            resetDesktop();
            desktop.add(apGUI);
            apGUI.ajustar(desktop.getSize());
        }
        else notificacaoPush("Você não possui a permissão necessária!");

    }//GEN-LAST:event_jMenuItem8ActionPerformed

    
    public static void notificacaoPush(String msg) {
        
        NotificacaoFade notificacao = new NotificacaoFade(msg);
        desktopS.removeAll();
        desktopS.repaint();
        desktopS.add(notificacao);        
        notificacao.ajustar(desktopS.getSize());
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            
            javax.swing.UIManager.put("Button.background",  java.awt.Color.white);  
            
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                
                
                if(Cerbero.decrypt64(Propriedade.getProp("museconfig.properties", "muse.video")).equalsIgnoreCase("true")) {
                    
                    if ("com.sun.java.swing.plaf.gtk.GTKLookAndFeel".equals(info.getClassName())) {   
                    
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }            
                }
                else {
                    
                    if ("Nimbus".equals(info.getName())) {                    
                    
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }                
                }
                
            }            
            
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Muse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Muse().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton bt_checkin;
    private javax.swing.JButton bt_checkout;
    private javax.swing.JButton bt_hospedes;
    private javax.swing.JButton bt_reservas;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JPanel lateral_direita;
    private javax.swing.JPanel lateral_esquerda;
    private javax.swing.JLabel lb_checkin;
    private javax.swing.JLabel lb_checkout;
    private javax.swing.JLabel lb_hospedes;
    private javax.swing.JLabel lb_reservas;
    private javax.swing.JPanel rodape;
    private javax.swing.JPanel topo;
    // End of variables declaration//GEN-END:variables
}
