/*
 * Projeto Muse.
 * Gerenciamento Hoteleiro
 *  I.T WORKS.
 */
package br.com.muse.gui;

import java.awt.Dimension;

/**
 *
 * @author kennedy
 */
public class NotificacaoFade extends javax.swing.JInternalFrame implements IPosicaoGUI{
    
    
    public String msg;

    /**
     * Creates new form NotificacaoFade
     * @param msg
     */
    public NotificacaoFade(String msg) {
        
        this.msg = msg;
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_msg = new javax.swing.JLabel();

        setBorder(null);
        setVisible(true);

        lb_msg.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        lb_msg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_msg.setText(this.msg);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_msg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_msg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lb_msg;
    // End of variables declaration//GEN-END:variables

    @Override
    public void ajustar(Dimension d) {        
        
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        
        this.setLocation(d.width-308, 8);
        this.setFocusable(false);
        GUIFX g = new GUIFX();        
        g.start();
        g.animar(this, GUIFX.EFEITO_DESAPARECER_PARA_DIREITA, 3000);
    }
}
